# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/kg540068/520_final/hardware/bd/DMA_block_design/DMA_block_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_block_design || ORIG_REF_NAME==DMA_block_design} -quiet] -quiet

# IP: c:/Users/kg540068/520_final/hardware/bd/DMA_block_design/ip/DMA_block_design_processing_system7_0_0/DMA_block_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_block_design_processing_system7_0_0 || ORIG_REF_NAME==DMA_block_design_processing_system7_0_0} -quiet] -quiet

# IP: c:/Users/kg540068/520_final/hardware/bd/DMA_block_design/ip/DMA_block_design_axi_dma_0_0/DMA_block_design_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_block_design_axi_dma_0_0 || ORIG_REF_NAME==DMA_block_design_axi_dma_0_0} -quiet] -quiet

# IP: c:/Users/kg540068/520_final/hardware/bd/DMA_block_design/ip/DMA_block_design_rst_ps7_0_50M_0/DMA_block_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_block_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==DMA_block_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: c:/Users/kg540068/520_final/hardware/bd/DMA_block_design/ip/DMA_block_design_ps7_0_axi_periph_0/DMA_block_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_block_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==DMA_block_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: c:/Users/kg540068/520_final/hardware/bd/DMA_block_design/ip/DMA_block_design_trafficgen_0_0/DMA_block_design_trafficgen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_block_design_trafficgen_0_0 || ORIG_REF_NAME==DMA_block_design_trafficgen_0_0} -quiet] -quiet

# IP: c:/Users/kg540068/520_final/hardware/bd/DMA_block_design/ip/DMA_block_design_axi_interconnect_0_0/DMA_block_design_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_block_design_axi_interconnect_0_0 || ORIG_REF_NAME==DMA_block_design_axi_interconnect_0_0} -quiet] -quiet

# IP: c:/Users/kg540068/520_final/hardware/bd/DMA_block_design/ip/DMA_block_design_auto_pc_1/DMA_block_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_block_design_auto_pc_1 || ORIG_REF_NAME==DMA_block_design_auto_pc_1} -quiet] -quiet

# IP: c:/Users/kg540068/520_final/hardware/bd/DMA_block_design/ip/DMA_block_design_auto_us_0/DMA_block_design_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_block_design_auto_us_0 || ORIG_REF_NAME==DMA_block_design_auto_us_0} -quiet] -quiet

# IP: c:/Users/kg540068/520_final/hardware/bd/DMA_block_design/ip/DMA_block_design_xbar_0/DMA_block_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_block_design_xbar_0 || ORIG_REF_NAME==DMA_block_design_xbar_0} -quiet] -quiet

# IP: c:/Users/kg540068/520_final/hardware/bd/DMA_block_design/ip/DMA_block_design_auto_pc_0/DMA_block_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_block_design_auto_pc_0 || ORIG_REF_NAME==DMA_block_design_auto_pc_0} -quiet] -quiet

# XDC: C:/Users/kg540068/520_final/hardware/bd/DMA_block_design/DMA_block_design_ooc.xdc
